FROM python:3.6.4

RUN apt-get update \
&&apt-get -y install freetds-dev \
&&apt-get -y install unixodbc-dev \
&&apt-get -y install git

COPY Mini-Blog /Mini-Blog 
WORKDIR /Mini-Blog
RUN python setting.py

CMD ["/bin/sh"]